cs425-groceryStore/core/urls.py
from django.urls import path
from . import views
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    EditProfileView
)

app_name = 'core'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('profile/edit', EditProfileView.as_view(), name='editprofile'),
    path('search/', views.search, name='search'),
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('deletecard/', views.deleteCard, name='deleteCard'),
    path('deleteShip/', views.deleteShip, name='deleteShip'),
    path('deleteBill/', views.deleteBill, name='deleteBill'),

]

cs425-groceryStore/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Grocery Store</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

cs425-groceryStore/templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

              <h3>Billing address</h3>

              <div class='hideable_billing_form'>
                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address' class='form-control' />
                  <label for="billing_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2' class='form-control' />
                  <label for="billing_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="billing_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>

                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                  <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
                </div>

              </div>

              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
                <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}
              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          {% include "order_snippet.html" %}
        </div>

      </div>

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');
var hideable_billing_form = $('.hideable_billing_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
var use_default_billing = document.querySelector("input[name=use_default_billing]");

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})

use_default_billing.addEventListener('change', function() {
  if (this.checked) {
    hideable_billing_form.hide();
  } else {
    hideable_billing_form.show();
  }
})

</script>
{% endblock extra_scripts %}

cs425-groceryStore/templates/editProfile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
      <!--Section: Products v.3-->
    <section class="text-center mb-4">
    <div class="content-section">
        {% if default_shipping_address %}<h2>default shipping address: {{ default_shipping_address.street_address }}</h2>{% endif %}
       {% if default_billing_address %}<h2>default billing address: {{ default_billing_address.street_address }}</h2>{% endif %}
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Modify/Add Address</legend>
              {{ form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info">Update Address</button>
          </div>

      </form>
    </div>
    </section>
</div>
{% endblock content %}

cs425-groceryStore/templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn"style="background-color:#333333">

    <hr class="my-4">

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="http://www.ezfire.me" target="_blank"> ezfire.me </a>
    </div>
    <!--/.Copyright-->

  </footer>

cs425-groceryStore/templates/home.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.productName }}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}

cs425-groceryStore/templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar" style="background-color:#333333">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">Grocery Store</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/profile">
              <span class="clearfix d-none d-sm-inline-block"> Profile </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
      </ul>
        <!-- implement search -->
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'core:search' %}">
            <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
      </div>

    </div>
  </nav>

cs425-groceryStore/templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.productName}}</h6>
        <small class="text-muted">{{ order_item.item.category}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

cs425-groceryStore/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.productName }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

cs425-groceryStore/templates/product.html
{% extends "base.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <img src="{{ item.image.url }}" class="img-fluid" alt="">
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <h2 href="">
                <strong>{{ object.productName }}</strong>
              </h2>
              <a>{{ object.category }}</a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

              {% if object.nutrition %}
            <p><br>Calories: {{ object.nutrition }}
              {% if object.alcohol_content %}
              <br>Alcohol Percentage: {{ object.alcohol_content }}%
              <br>Weight: {{ object.size }} grams
              {% endif %}
              {% endif %}
            </p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

cs425-groceryStore/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
      <!--Section: Products v.3-->
    <section class="text-center mb-4">
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
            <h2 class="text-secondary">balance:${{ userprofile.balance }}</h2>
           <h1>Modify/Create/Delete Details</h1>
        </div>
      </div>
      <form  action="{% url 'core:editprofile' %}">
          <div class="form-group">
              <button class="btn btn-outline-info">Update Address</button>
          </div>
      </form>
        <form  action="{% url 'core:deleteShip' %}">
          <div class="form-group">
              <button class="btn btn-outline-info">Delete Shipping Address</button>
          </div>
      </form>
        <form  action="{% url 'core:deleteBill' %}">
          <div class="form-group">
              <button class="btn btn-outline-info">Delete Billing Address</button>
          </div>
      </form>
        <form  action="{% url 'core:deleteCard' %}">
          <div class="form-group">
              <button class="btn btn-outline-info">Delete Card</button>
          </div>
      </form>
    </div>
    </section>
</div>
{% endblock content %}

cs425-groceryStore/templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

cs425-groceryStore/templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>

cs425-groceryStore/templates/search.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in items %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.productName }}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}